# Site settings
name: Mike
email: zhangrunwei@aliyun.com

my_bokeyuan: https://www.cnblogs.com/Mike_Chang/
github: https://github.com/ChangMike?tab=repositories
baseurl: "/blogs"
motto: The real freedom is to be able to control yourself at all times.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ChangMike

# Baidu settings
# 百度推广账号登陆名：MikeChang
baidu_analysis: f72db1ee092e2e37a2012b00006e38d3

markdown: kramdown


